kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: node
  commands:
    - npm install
    - npm test:coverage
- name: docker  
  image: plugins/docker
  settings:
    username: alexham
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: alexham/home-hub
    tags: latest